# Generated by Django 2.2.3 on 2019-07-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('kind', models.CharField(choices=[('english', '英国紅茶'), ('chinese', '中国紅茶'), ('japanese', '日本茶')], max_length=255, verbose_name='種類')),
            ],
        ),
    ]
