version: 2
jobs: 
  build:
    docker:
      - image: circleci/python:3.6
    working_directory: ./
    steps:
      # ソースコードのチャックアウト
      - checkout
      # unittestコマンドの実行
      - run: python test_calculaitons.py