version: 2
jobs: 
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      # ソースコードのチャックアウト
      - checkout
      - run: |
          python3.7 -m venv venv
          source ./venv/bin/activate
          # pytestのインストール
          pip install django
          cd cafe/apps
          # マイグレーションの実行
          python manage.py migrate
          # Djangoのテストを実行
          python manage.py test